export const KO_EN = {
  // === Составные / длинные термины ===
  '자동변속기':'Automatic Transmission','수동변속기':'Manual Transmission',
  '크로스멤버':'Crossmember','테일게이트':'Tailgate',
  '레인포스먼트':'Reinforcement','인스트루먼트':'Instrument',
  '멀티펑션':'Multifunction','콤비네이션':'Combination',
  '스태빌라이저':'Stabilizer','아웃사이드':'Outside',
  '웨이스트라인':'Waistline','와이어링':'Wiring',
  '스티어링':'Steering','에이프런':'Apron',
  '라디에이터':'Radiator','스페이서':'Spacer',
  '익스텐션':'Extension','어셈블리':'Assembly',
  '컴플리트':'Complete','블랭킹':'Blanking',
  '마운팅':'Mounting','스토퍼':'Stopper',
  '브레이크':'Brake','클러스터':'Cluster',
  '머풀러':'Muffler','와이퍼':'Wiper',
  '에어컨':'Air Conditioner','가니쉬':'Garnish',
  '컨버터':'Converter','제너레이터':'Generator',
  '얼터네이터':'Alternator','트랜스미션':'Transmission',
  '서스펜션':'Suspension','서모스탯':'Thermostat',
  '컴프레서':'Compressor','콘덴서':'Condenser',
  '이배포레이터':'Evaporator','매니폴드':'Manifold',
  '인터쿨러':'Intercooler','터보차저':'Turbocharger',
  '카탈라이저':'Catalytic Converter','인젝터':'Injector',
  '솔레노이드':'Solenoid','레귤레이터':'Regulator',
  '텐셔너':'Tensioner','알터네이터':'Alternator',
  '크러쉬':'Crush Pad','리테이너':'Retainer',
  '인슐레이터':'Insulator','프로텍터':'Protector',
  '어큐뮬레이터':'Accumulator','리저버':'Reservoir',
  '앰프리파이어':'Amplifier','스피커':'Speaker',
  '안테나':'Antenna','네비게이션':'Navigation',
  '디스플레이':'Display','인디케이터':'Indicator',
  '선바이저':'Sun Visor','아이들러':'Idler',
  '트랜스퍼':'Transfer','디퍼렌셜':'Differential',
  '프로펠러':'Propeller','드라이브':'Drive',
  '쉬프트':'Shift','오토매틱':'Automatic',
  '클러치':'Clutch','싱크로나이저':'Synchronizer',
  '플라이':'Fly',
  '피스톤':'Piston','캠샤프트':'Camshaft',
  '밸브트레인':'Valve Train','타이밍':'Timing',
  '크랭크샤프트':'Crankshaft','실린더헤드':'Cylinder Head',
  '인테이크':'Intake','엑스하우스트':'Exhaust',
  '이그니션':'Ignition','글로우플러그':'Glow Plug',
  '스파크':'Spark','노즐':'Nozzle',
  '인터셉터':'Interceptor','바이패스':'Bypass',
  '캘리퍼':'Caliper','디스크':'Disc',
  '마스터':'Master','부스터':'Booster',
  '파킹':'Parking','브레이킹':'Braking',
  '쇼크업소버':'Shock Absorber','스트럿':'Strut',
  '부싱':'Bushing','스웨이':'Sway',
  '볼조인트':'Ball Joint',
  '로커':'Rocker','필러':'Filler','레인':'Rain',
  '스포일러':'Spoiler','디퓨저':'Diffuser',
  '스커트':'Skirt','사이드스텝':'Side Step',
  '웨더스트립':'Weatherstrip','스트립':'Strip',
  '엠블럼':'Emblem','네임플레이트':'Nameplate',
  '릴레이':'Relay','퓨즈':'Fuse',
  '액추에이터':'Actuator','솔레로이드':'Solenoid',
  '래치':'Latch','록':'Lock',
  '헤드램프':'Headlamp','포그':'Fog',
  '테일':'Tail','시그널':'Signal',
  '턴':'Turn','데이타임':'Daytime',
  '리플렉터':'Reflector','프로젝터':'Projector',
  '벌브':'Bulb','바이제논':'Bi-Xenon',
  '할로겐':'Halogen','엘이디':'LED',
  '블로워':'Blower','팬':'Fan',
  '에바포레이터':'Evaporator','드라이어':'Dryer',
  '덕트':'Duct','벤트':'Vent',
  '레지스터':'Resistor',
  '캐탈리스트':'Catalyst','엑조스트':'Exhaust',
  '리어머플러':'Rear Muffler','프론트파이프':'Front Pipe',
  '브라켓':'Bracket','브라케트':'Bracket','브래킷':'Bracket',
  '리어':'Rear','프론트':'Front','좌측':'Left','우측':'Right',
  '아우터':'Outer','아웃터':'Outer','인너':'Inner',
  '센터':'Center','어퍼':'Upper','로어':'Lower','로워':'Lower',
  '도어':'Door','판넬':'Panel','커버':'Cover','몰딩':'Molding',
  '범퍼':'Bumper','펜더':'Fender','루프':'Roof','트렁크':'Trunk',
  '후드':'Hood','필라':'Pillar','카울':'Cowl',
  '사이드':'Side','바디':'Body','플로어':'Floor','쿼터':'Quarter',
  '윈도우':'Window','글라스':'Glass','데크':'Deck',
  '라벨':'Label','커넥터':'Connector','케이블':'Cable',
  '호스':'Hose','튜브':'Tube','파이프':'Pipe',
  '볼트':'Bolt','너트':'Nut','와셔':'Washer',
  '클립':'Clip','캡':'Cap','플러그':'Plug',
  '스프링':'Spring','패드':'Pad','플레이트':'Plate',
  '힌지':'Hinge','레일':'Rail','가드':'Guard',
  '베어링':'Bearing','링':'Ring','핀':'Pin',
  '엔진':'Engine','미션':'Transmission','샤프트':'Shaft',
  '실린더':'Cylinder','크랭크':'Crankshaft',
  '오일':'Oil','필터':'Filter','펌프':'Pump',
  '연료':'Fuel','퓨얼':'Fuel','필러':'Filler',
  '액슬':'Axle','멤버':'Member',
  '휠':'Wheel','암':'Arm','댐퍼':'Damper',
  '스위치':'Switch','센서':'Sensor','모듈':'Module',
  '램프':'Lamp','히터':'Heater','에어':'Air',
  '배터리':'Battery','컨트롤':'Control','유니트':'Unit',
  '콘솔':'Console','파워':'Power',
  '시트':'Seat','트림':'Trim',
  '미러':'Mirror','뷰':'View','핸들':'Handle','레버':'Lever',
  '리드':'Lid','행거':'Hanger','스크류':'Screw',
  '밸브':'Valve','헤드':'Head','블록':'Block',
  '로드':'Rod','조인트':'Joint','너클':'Knuckle',
  '체커':'Checker','세트':'Set','서브':'Sub',
  '상부':'Upper','하부':'Lower','좌':'Left','우':'Right',
  '앞':'Front','뒤':'Rear','메인':'Main',
  '실':'Seal','이코노미':'Economy',
  '플로워':'Floor','크로스':'Cross','프레임':'Frame',
  '탱크':'Tank','서포트':'Support','대쉬':'Dash',
  '가스켓':'Gasket','언더':'Under',
  '박스':'Box','모터':'Motor','몰드':'Mold',
  '룸':'Room','백':'Back','바':'Bar',
  '커튼':'Curtain','벨트':'Belt',
  '라이너':'Liner','패널':'Panel',
  '피팅':'Fitting','매트':'Mat',
  '프레셔':'Pressure','그릴':'Grille',
  '루버':'Louver','노브':'Knob',
  '디플렉터':'Deflector','씰':'Seal',
  '와이어':'Wire','아암':'Arm',
  '하우징':'Housing','바운드':'Bound',
  '캐리어':'Carrier','로터':'Rotor',
  '토크':'Torque','리프트':'Lift',
  '칼라':'Collar','부트':'Boot',
  '클램프':'Clamp','러버':'Rubber',
  '스터드':'Stud','피니언':'Pinion',
  '렉':'Rack','락':'Lock',
  '래디에이터':'Radiator','쿠션':'Cushion',
  '니들':'Needle','플랜지':'Flange',
  '펜':'Fender','케이스':'Case',
  '블레이드':'Blade','아웃렛':'Outlet',
  '인렛':'Inlet','리턴':'Return',
  '가이드':'Guide','스톱':'Stop',
  '노크':'Knock','오투':'O2',
  '크리프':'Creep','레지스트':'Resist',
  '미들':'Middle','로우':'Low','하이':'High',
  '톱':'Top','보텀':'Bottom',
  '트랜스':'Transfer','액셀':'Accelerator',
  '슬라이딩':'Sliding','폴딩':'Folding',
  '테이프':'Tape','스티커':'Sticker',
  '프라이머':'Primer','실러':'Sealer',
  '러그':'Lug','마스크':'Mask',
  '벤딩':'Bending','포밍':'Forming',
  '글로브':'Glove','대시보드':'Dashboard',
  '암레스트':'Armrest','헤드레스트':'Headrest',
  '카펫':'Carpet','카고':'Cargo',
  '라이트':'Light','스카프':'Scuff',
  '오버헤드':'Overhead','선루프':'Sunroof',
  '파노라마':'Panoramic',
  '캐니스터':'Canister','인젝션':'Injection',
  '레귤레이타':'Regulator','스로틀':'Throttle',
  '카뷰레터':'Carburetor','터빈':'Turbine',
  '워터':'Water','쿨링':'Cooling',
  '쿨러':'Cooler','라인':'Line',
  '써모':'Thermo','그로메트':'Grommet',
  '오링':'O-Ring','시일':'Seal',
  '매니':'Manifold','다이아프램':'Diaphragm',
  '타이로드':'Tie Rod','엔드':'End',
  '마운트':'Mount','번호':'Number',
  '이씨유':'ECU','컴퓨터':'Computer',
  '메모리':'Memory','프로세서':'Processor',
  '커플링':'Coupling','클래스':'Class',
  '스틸':'Steel','알루미늄':'Aluminum',
  '크롬':'Chrome','매직':'Magic',
  '더블':'Double','싱글':'Single',
  '하이브리드':'Hybrid','디젤':'Diesel',
  '가솔린':'Gasoline',
  '키트':'Kit','키':'Key','기어':'Gear',
  '스냅':'Snap','와이드':'Wide',
  '롱':'Long','숏':'Short',
  '라운드':'Round','플랫':'Flat',
  '스퀘어':'Square','헥사':'Hex',
  '밴드':'Band','슬리브':'Sleeve',
  '조절':'Adjusting','고정':'Fixed',
  '교체':'Replacement','보수':'Repair',
  '스탠다드':'Standard','옵션':'Option',
  '에이비에스':'ABS','에스알에스':'SRS',
  '하네스':'Harness','커플러':'Coupler',
  '피씨비':'PCB','칩':'Chip',
  '아답터':'Adapter','익스팬션':'Expansion',
  '어저스터':'Adjuster','레시버':'Receiver',
  '바이브레이터':'Vibration Damper','밸런서':'Balancer',
  '스프로켓':'Sprocket','체인':'Chain',
  '벨로우즈':'Bellows','부츠':'Boot',
  '차져':'Charger','인버터':'Inverter',
  '하이드릭':'Hydraulic','뉴매틱':'Pneumatic',
  '로크':'Lock','인터락':'Interlock',
  '디텐트':'Detent','래칫':'Ratchet',
  '스플라인':'Spline','테이퍼':'Taper',
  '저널':'Journal','피봇':'Pivot',
  '임펠러':'Impeller','로브':'Lobe',
  '베젤':'Bezel','라디오':'Radio','버클':'Buckle',
  '에어백':'Airbag','쉴드':'Shield',
  '패시아':'Fascia','인사이드':'Inside',
  '태핏':'Tappet','홀더':'Holder',
  '세퍼레이터':'Separator','리버스':'Reverse',
  '오토':'Auto','및':'&',
  '쉼':'Shim','스크린':'Screen',
  '풀리':'Pulley','플라이휠':'Flywheel',
  '매니폴드':'Manifold','캠':'Cam',
  '로터리':'Rotary','피드':'Feed',
  '프리':'Free','포지션':'Position',
  '플런저':'Plunger','오버':'Over',
  '인터':'Inter','엑스':'X',
  '트레이':'Tray','빔':'Beam',
  '넘버':'Number','타입':'Type','사이즈':'Size',
  '스트레이너':'Strainer','쿨란트':'Coolant',
  '리저버탱크':'Reservoir Tank',
  '와이퍼모터':'Wiper Motor',
  '하이패스':'Hi-Pass','네트':'Net',
  '트레일링':'Trailing','리딩':'Leading',
  '옵셋':'Offset',
  '아치':'Arch','사이렌':'Siren',
  '멀티':'Multi','듀얼':'Dual',
  '서큘레이팅':'Circulating','바이':'By',
  '프리히터':'Pre-Heater','애프터':'After',
  '이머전시':'Emergency','벤틸레이터':'Ventilator',
  '템프러처':'Temperature','리모콘':'Remote Control',
  '배너티':'Vanity','트랙':'Track',
  '비디오':'Video','일렉트로닉':'Electronic',
  '하이드로릭':'Hydraulic','쇼크':'Shock',
  '업소버':'Absorber','서모':'Thermo',
  '베이퍼':'Vapor','석션':'Suction',
  '쉬라우드':'Shroud','컨트롤러':'Controller',
  '앗세이':'Assembly','볼':'Ball',
  '피치':'Pitch','혼':'Horn',
  '스티어링휠':'Steering Wheel',
  '비스커스':'Viscous','크랭크케이스':'Crankcase',
  '로킹':'Locking','디밍':'Dimming',
  '인터쿨러호스':'Intercooler Hose',
  '컨트롤유니트':'Control Unit',
  '스티어링컬럼':'Steering Column',
  '리어콤비네이션':'Rear Combination',
  '순정':'Genuine','운전석':'Driver Side','조수석':'Passenger Side',
  '흡입':'Suction','서모스타트':'Thermostat',
  '외장':'Exterior','맵':'Map','글래스':'Glass',
  '앰프':'Amplifier','울트라소닉':'Ultrasonic',
  '버튼':'Button','오토메틱':'Automatic',
  '스텝':'Step','크래쉬패드':'Crash Pad',
  '슬라이드':'Slide','앵커':'Anchor',
  '헤드라이닝':'Headlining','아이':'Eye',
  '고압':'High Pressure','페달':'Pedal',
  '스포터':'Spot','리조네이터':'Resonator',
  '커넥팅':'Connecting','배기':'Exhaust',
  '클리너':'Cleaner','드럼':'Drum',
  '컬럼':'Column','왼쪽':'Left','오른쪽':'Right',
  '스트러트':'Strut','메뉴얼':'Manual',
  '오버드라이브':'Overdrive','스피드':'Speed',
  '카올':'Cowl','에이프론':'Apron',
  '리퀴드':'Liquid','언록':'Unlock',
  '마이크':'Microphone','핸즈프리':'Hands-Free',
  '비추얼':'Virtual','사운드':'Sound',
  '시스템':'System','프런트':'Front',
  '스캘프':'Scalp','게이트':'Gate',
  '하이트':'Height','어드져스트':'Adjust',
  '크래쉬':'Crash','어세블리':'Assembly',
  '투':'To','머시닝':'Machining',
  '팩':'Pack','프레져':'Pressure',
  '보디':'Body','쇼트':'Short',
  '토탈':'Total','브러쉬':'Brush',
  '내측':'Inner','외측':'Outer',
  '오디오':'Audio','소켓':'Socket','시가':'Cigar',
  '라이터':'Lighter','밧데리':'Battery',
  '페드':'Fed','페어':'Pair',
  '토션':'Torsion','리모트':'Remote',
  '악세사리':'Accessory','스커프':'Scuff',
  '리클라이너':'Recliner','어시스터':'Assist',
  '델타':'Delta','흡기':'Intake',
  '진공':'Vacuum','쿨런트':'Coolant',
  '버큠':'Vacuum','링크':'Link',
  '인풋':'Input','디퍼런셜':'Differential',
  '테드':'Heated','리클라이닝':'Reclining',
  '어시스트':'Assist','액세서리':'Accessory',
  '셀프':'Self',
  '스탑':'Stop','바큠':'Vacuum',
  '포트':'Port','체크':'Check',
  '플랩':'Flap','인히비터':'Inhibitor',
  '스타터':'Starter',
  '다이나모':'Dynamo','워셔':'Washer',
  '백업':'Backup','리버싱':'Reversing',
  '나로우':'Narrow','스몰':'Small','라지':'Large',
  '하프':'Half','풀':'Full',
  '매뉴얼':'Manual','리턴스프링':'Return Spring',
  '리테이닝':'Retaining','세퍼레이팅':'Separating',
  '이젝터':'Ejector','디스트리뷰터':'Distributor',
  '어저스팅':'Adjusting',
  '플렉시블':'Flexible','유니버셜':'Universal',
  '익스팬션밸브':'Expansion Valve',
  '레시버드라이어':'Receiver Dryer',
  '로워암':'Lower Arm','어퍼암':'Upper Arm',
  '타이밍벨트':'Timing Belt','타이밍체인':'Timing Chain',
  '크랭크풀리':'Crank Pulley','캠풀리':'Cam Pulley',
  '드라이브벨트':'Drive Belt',
  '워터펌프':'Water Pump','오일펌프':'Oil Pump',
  '연료펌프':'Fuel Pump','파워스티어링':'Power Steering',
  '에어필터':'Air Filter','오일필터':'Oil Filter',
  '연료필터':'Fuel Filter',
  '디프로스터':'Defroster','모드':'Mode',
  '리모컨':'Remote Control','임팩트':'Impact',
  '카페트':'Carpet','앤티':'Anti',
  '그립':'Grip','웨스트':'Waist',
  '익죠스트':'Exhaust','레벨':'Level',
  '게이지':'Gauge','오버홀':'Overhaul',
  '링D':'Ring D','서어지':'Surge',
  '마그넷':'Magnet','캡슐':'Capsule',
  '셕션':'Section','트랜지스터':'Transistor',
  '크리스탈':'Crystal','스프레이':'Spray',
  '리시버':'Receiver','코일':'Coil',
  '코어':'Core','리프':'Leaf',
  '니플':'Nipple','티':'Tee',
  '엘보':'Elbow','유니온':'Union',
  '리듀서':'Reducer',
  '어댑터':'Adapter','스트레이트':'Straight',
  '록킹':'Locking','솔밸브':'Sol Valve',
  '카운터':'Counter','커트':'Cut',
  '리미트':'Limit','프레스':'Press',
  '잠금해제':'Unlock','윈드쉴드':'Windshield',
  '파워윈도우':'Power Window','유닛':'Unit',
  '아이솔레이션':'Isolation','산소센서':'Oxygen Sensor',
  '터미널':'Terminal','중앙':'Center',
  '스테이':'Stay','메니폴더':'Manifold',
  '일렉트로릭':'Electronic','하이드로':'Hydro',
  '허브':'Hub','드리븐':'Driven',
  '히트':'Heat','레이스':'Race',
  '시스':'System',
  '플레이':'Play','스크래치':'Scratch',
  '웜':'Worm','기어박스':'Gearbox',
  '크로스오버':'Crossover','리액터':'Reactor',
  '아웃풋':'Output','카본':'Carbon',
  '세라믹':'Ceramic','타이타늄':'Titanium',
  '나일론':'Nylon','폴리':'Poly',
  '캐빈':'Cabin','모니터':'Monitor',
  '엘리먼트':'Element','악셀레이터':'Accelerator',
  '콘트롤':'Control','상단':'Top',
  '스타트':'Start','컨넥터':'Connector',
  '스트라이커':'Striker','컵':'Cup',
  '데칼':'Decal','클럽':'Club','피플':'People',
  '플레니트':'Planet','아웃':'Out',
  '열':'Row',
  '코션':'Caution','틸팅':'Tilting',
  '키보드':'Keyboard','앤드':'End',
  '사일렌서':'Silencer',
  '에어 백':'Airbag',
  '거싯':'Gusset','훅':'Hook',
  '무선':'Wireless','충전':'Charging',
  '샤워':'Shower','번호판등':'License Plate Light',
  '커터':'Cutter','어셈불리':'Assembly',
  '탑':'Top','컵버':'Cover',
  '릴리프':'Relief','텐션':'Tension',
  '업':'Up',
  '히팅':'Heating','보조안전장치':'Safety Device',
  '로고':'Logo','넥':'Neck',
  '프로텍트':'Protect',
  '쉬트':'Sheet','스페어':'Spare',
  '트랜스미터':'Transmitter',
  '이베퍼레이터':'Evaporator',
  '액츄에이터':'Actuator',
  '컨디셔닝':'Conditioning',
  '요레이트':'Yaw Rate',
  '정션':'Junction',
  '언터':'Under',
  '배플':'Baffle',
  '프리미엄':'Premium','활성탄':'Activated Carbon',
  '더스트':'Dust','튜너':'Tuner',
  '러기지':'Luggage','포켓':'Pocket',
  '렉티파이어':'Rectifier','부쉬':'Bush',
  '블럭':'Block','써브':'Sub',
  '패치':'Patch','레인프':'Reinforcement',
  '에어백':'Airbag',
  '드라이버':'Driver','링키지':'Linkage',
  '드레인':'Drain','레벨링':'Leveling',
  '리브드':'Ribbed','스포츠':'Sports',
  '타이어':'Tire','하이드로닉':'Hydronic',
  '앗셈블리':'Assembly','앗세이':'Assembly','아세이':'Assembly',
  '호스어셈블리':'Hose Assembly',
  '하이마운팅스탑':'High Mounting Stop',
  '패시어':'Fascia',
  '베이퍼라이져':'Vaporizer',
  '브리더':'Breather','래터럴':'Lateral',
  '머플러':'Muffler','스탠션':'Stanchion',
  '페이셔':'Fascia','볼륨':'Volume',
  '시디':'CD','체인져':'Changer','체인저':'Changer',
  '타임':'Time','알람':'Alarm',
  '저압':'Low Pressure','고정용':'Fixing',
  '후단':'Rear','낙스':'NOx',
  '미니':'Mini','리시빙':'Receiving',
};

export function tr(name) {
  let r = name;
  const keys = Object.keys(KO_EN).sort((a, b) => b.length - a.length);
  for (const k of keys) {
    if (k.length <= 2 && /[가-힯]/.test(k)) {
      r = r.replace(new RegExp('(?<=^|\\s)' + k + '(?=$|\\s)', 'g'), KO_EN[k]);
    } else {
      r = r.replaceAll(k, KO_EN[k]);
    }
  }
  return r.trim();
}
