// Словарь моделей авто KO→EN + бренды. Ревью: 2026-07-05
// Романизированные корейские названия (решение владельца).

export const MODELS = {
  // === Hyundai легковые ===
  '쏘나타': { en: 'Sonata', brand: 'hyundai' },
  '그랜저': { en: 'Grandeur', brand: 'hyundai' },
  '그랜져': { en: 'Grandeur', brand: 'hyundai' }, // опечатка
  '아반떼': { en: 'Avante', brand: 'hyundai' },
  '엘란트라': { en: 'Elantra', brand: 'hyundai' },
  '싼타페': { en: 'Santa Fe', brand: 'hyundai' },
  '투싼': { en: 'Tucson', brand: 'hyundai' },
  '코나': { en: 'Kona', brand: 'hyundai' },
  '스타렉스': { en: 'Starex', brand: 'hyundai' },
  '포터': { en: 'Porter', brand: 'hyundai' },
  '아이오닉': { en: 'Ioniq', brand: 'hyundai' },
  '에쿠스': { en: 'Equus', brand: 'hyundai' },
  '벨로스터': { en: 'Veloster', brand: 'hyundai' },
  '엑센트': { en: 'Accent', brand: 'hyundai' },
  '베르나': { en: 'Verna', brand: 'hyundai' },
  '스타리아': { en: 'Staria', brand: 'hyundai' },
  '갤로퍼': { en: 'Galloper', brand: 'hyundai' },
  '팰리세이드': { en: 'Palisade', brand: 'hyundai' },
  '쿠페': { en: 'Coupe', brand: 'hyundai' },
  '베라크루즈': { en: 'Veracruz', brand: 'hyundai' },
  '투스카니': { en: 'Tuscani', brand: 'hyundai' },
  '클릭': { en: 'Click', brand: 'hyundai' },
  '트라제': { en: 'Trajet', brand: 'hyundai' },
  '리베로': { en: 'Libero', brand: 'hyundai' },
  '맥스크루즈': { en: 'Maxcruz', brand: 'hyundai' },
  '라비타': { en: 'Lavita', brand: 'hyundai' },
  '아슬란': { en: 'Aslan', brand: 'hyundai' },
  '캐스퍼': { en: 'Casper', brand: 'hyundai' },
  '베뉴': { en: 'Venue', brand: 'hyundai' },
  '테라칸': { en: 'Terracan', brand: 'hyundai' },
  '쏠라티': { en: 'Solati', brand: 'hyundai' },
  '아토스': { en: 'Atos', brand: 'hyundai' },
  '티뷰론': { en: 'Tiburon', brand: 'hyundai' },
  '넥쏘': { en: 'Nexo', brand: 'hyundai' },
  '마르샤': { en: 'Marcia', brand: 'hyundai' },
  '싼타모': { en: 'Santamo', brand: 'hyundai' },
  '다이너스티': { en: 'Dynasty', brand: 'hyundai' },
  '그레이스': { en: 'Grace', brand: 'hyundai' },
  '블루온': { en: 'BlueOn', brand: 'hyundai' },
  '제네시스 쿠페': { en: 'Genesis Coupe', brand: 'hyundai' },
  '스쿠프': { en: 'Scoupe', brand: 'hyundai' },
  '베르나': { en: 'Verna', brand: 'hyundai' },
  '갤로퍼2': { en: 'Galloper 2', brand: 'hyundai' },
  '제네시스 G70': { en: 'Genesis G70', brand: 'genesis' },
  '제네시스 G80': { en: 'Genesis G80', brand: 'genesis' },
  '제네시스 더올뉴 G80': { en: 'Genesis The All New G80', brand: 'genesis' },
  '제네시스 G90': { en: 'Genesis G90', brand: 'genesis' },
  '제네시스 GV60': { en: 'Genesis GV60', brand: 'genesis' },
  '제네시스 GV70': { en: 'Genesis GV70', brand: 'genesis' },
  '제네시스 GV80': { en: 'Genesis GV80', brand: 'genesis' },
  '제네시스 EQ900': { en: 'Genesis EQ900', brand: 'genesis' },
  '제네시스': { en: 'Genesis', brand: 'genesis' },
  'G70': { en: 'Genesis G70', brand: 'genesis' },
  'G80': { en: 'Genesis G80', brand: 'genesis' },
  'G90': { en: 'Genesis G90', brand: 'genesis' },
  'GV60': { en: 'Genesis GV60', brand: 'genesis' },
  'GV70': { en: 'Genesis GV70', brand: 'genesis' },
  'GV80': { en: 'Genesis GV80', brand: 'genesis' },
  'EQ900': { en: 'Genesis EQ900', brand: 'genesis' },
  'EV6': { en: 'EV6', brand: 'kia' },
  'EV9': { en: 'EV9', brand: 'kia' },
  '포르테/쿱': { en: 'Forte/Koup', brand: 'kia' },
  'I30/I30CW': { en: 'i30/i30CW', brand: 'hyundai' },
  '그랜저/다이너스티': { en: 'Grandeur/Dynasty', brand: 'hyundai' },
  'E마이티': { en: 'E-Mighty', brand: 'hyundai' },
  'E카운티': { en: 'E-County', brand: 'hyundai' },
  'E에어로타운': { en: 'E-Aero Town', brand: 'hyundai' },
  'i30': { en: 'i30', brand: 'hyundai' },
  'I30': { en: 'i30', brand: 'hyundai' },
  'i40': { en: 'i40', brand: 'hyundai' },
  'I40': { en: 'i40', brand: 'hyundai' },
  'i20': { en: 'i20', brand: 'hyundai' },
  'ix35': { en: 'ix35', brand: 'hyundai' },
  'ix55': { en: 'ix55', brand: 'hyundai' },
  '그랜드 스타렉스': { en: 'Grand Starex', brand: 'hyundai' },
  '슈퍼 에어로 시티': { en: 'Super Aero City', brand: 'hyundai' },
  '에어로 시티': { en: 'Aero City', brand: 'hyundai' },
  '봉고 프론티어': { en: 'Bongo Frontier', brand: 'kia' },
  'VENUE': { en: 'Venue', brand: 'hyundai' },

  // === Hyundai коммерческие ===
  '마이티': { en: 'Mighty', brand: 'hyundai' },
  '메가트럭': { en: 'Mega Truck', brand: 'hyundai' },
  '파워트럭': { en: 'Power Truck', brand: 'hyundai' },
  '슈퍼트럭': { en: 'Super Truck', brand: 'hyundai' },
  '트라고 엑시언트': { en: 'Trago Xcient', brand: 'hyundai' },
  '트라고': { en: 'Trago', brand: 'hyundai' },
  '엑시언트': { en: 'Xcient', brand: 'hyundai' },
  '메가 트럭': { en: 'Mega Truck', brand: 'hyundai' },
  '에어로 퀸/익스프레스': { en: 'Aero Queen/Express', brand: 'hyundai' },
  '에어로 퀸': { en: 'Aero Queen', brand: 'hyundai' },
  'E마이티/마이티': { en: 'E-Mighty/Mighty', brand: 'hyundai' },
  '포르테/포르테 쿱 08': { en: 'Forte/Forte Koup 08', brand: 'kia' },
  '포르테/포르테 쿱': { en: 'Forte/Forte Koup', brand: 'kia' },
  '봉고3/프레지오': { en: 'Bongo 3/Pregio', brand: 'kia' },
  'K3 21': { en: 'K3 MY21', brand: 'kia' },
  '그린시티': { en: 'Green City', brand: 'hyundai' },
  '글로벌900/그린시티': { en: 'Global 900/Green City', brand: 'hyundai' },
  '글로벌900': { en: 'Global 900', brand: 'hyundai' },
  '유니버스': { en: 'Universe', brand: 'hyundai' },
  '에어로': { en: 'Aero', brand: 'hyundai' },
  '에어로타운': { en: 'Aero Town', brand: 'hyundai' },
  '카운티': { en: 'County', brand: 'hyundai' },
  '코러스': { en: 'Chorus', brand: 'hyundai' },
  '그린시티': { en: 'Green City', brand: 'hyundai' },

  // === Kia ===
  'K3': { en: 'K3', brand: 'kia' },
  'K5': { en: 'K5', brand: 'kia' },
  'K7': { en: 'K7', brand: 'kia' },
  'K8': { en: 'K8', brand: 'kia' },
  'K9': { en: 'K9', brand: 'kia' },
  '쏘렌토': { en: 'Sorento', brand: 'kia' },
  '스포티지': { en: 'Sportage', brand: 'kia' },
  '카니발': { en: 'Carnival', brand: 'kia' },
  '모닝': { en: 'Morning', brand: 'kia' },
  '쏘울': { en: 'Soul', brand: 'kia' },
  '니로': { en: 'Niro', brand: 'kia' },
  '셀토스': { en: 'Seltos', brand: 'kia' },
  '스토닉': { en: 'Stonic', brand: 'kia' },
  '레이': { en: 'Ray', brand: 'kia' },
  '모하비': { en: 'Mohave', brand: 'kia' },
  '오피러스': { en: 'Opirus', brand: 'kia' },
  '로체': { en: 'Lotze', brand: 'kia' },
  '쎄라토': { en: 'Cerato', brand: 'kia' },
  '포르테': { en: 'Forte', brand: 'kia' },
  '프라이드': { en: 'Pride', brand: 'kia' },
  '카렌스': { en: 'Carens', brand: 'kia' },
  '스팅어': { en: 'Stinger', brand: 'kia' },
  '봉고': { en: 'Bongo', brand: 'kia' },
  '프레지오': { en: 'Pregio', brand: 'kia' },
  '비스토': { en: 'Visto', brand: 'kia' },
  '옵티마': { en: 'Optima', brand: 'kia' },
  '세피아': { en: 'Sephia', brand: 'kia' },
  '슈마': { en: 'Shuma', brand: 'kia' },
  '스펙트라': { en: 'Spectra', brand: 'kia' },
  '리오': { en: 'Rio', brand: 'kia' },
  '프론티어': { en: 'Frontier', brand: 'kia' },
  '그랜버드': { en: 'Granbird', brand: 'kia' },
  '엔터프라이즈': { en: 'Enterprise', brand: 'kia' },
  '포텐샤': { en: 'Potentia', brand: 'kia' },
  '카스타': { en: 'Carstar', brand: 'kia' },
  '크레도스': { en: 'Credos', brand: 'kia' },
  '타우너': { en: 'Towner', brand: 'kia' },
  '캐피탈': { en: 'Capital', brand: 'kia' },
  '콩코드': { en: 'Concord', brand: 'kia' },
  '아벨라': { en: 'Avella', brand: 'kia' },

  // === SsangYong / прочие (универсальные запчасти) ===
  '코란도': { en: 'Korando', brand: 'ssangyong' },
  '렉스턴': { en: 'Rexton', brand: 'ssangyong' },
  '티볼리': { en: 'Tivoli', brand: 'ssangyong' },
  '로디우스': { en: 'Rodius', brand: 'ssangyong' },
  '투리스모': { en: 'Turismo', brand: 'ssangyong' },
  '액티언': { en: 'Actyon', brand: 'ssangyong' },
  '카이런': { en: 'Kyron', brand: 'ssangyong' },
  '무쏘': { en: 'Musso', brand: 'ssangyong' },
  '체어맨': { en: 'Chairman', brand: 'ssangyong' },
  '아우디': { en: 'Audi', brand: 'audi' },
};

// Префиксы поколений/фейслифтов (порядок важен: длинные раньше)
export const PREFIXES = [
  ['디 올 뉴', 'The All New'],
  ['디 올뉴', 'The All New'],
  ['디올뉴', 'The All New'],
  ['디올 뉴', 'The All New'],
  ['더 올 뉴', 'The All New'],
  ['더 올뉴', 'The All New'],
  ['더올뉴', 'The All New'],
  ['더 뉴', 'The New'],
  ['더뉴', 'The New'],
  ['올 뉴', 'All New'],
  ['올뉴', 'All New'],
  ['뉴', 'New'],
  ['더', 'The'],
];

// Маркетинговые суффиксы/подварианты
export const SUBNAMES = {
  '디 엣지': 'The Edge',
  '엣지': 'Edge',
  '뉴라이즈': 'New Rise',
  '프리미어': 'Premier',
  '더 프라임': 'The Prime',
  '프라임': 'Prime',
  '더 스타일': 'The Style',
  '스타일': 'Style',
  '더 볼드': 'The Bold',
  '볼드': 'Bold',
  '마이스터': 'Meister',
  '트랜스폼': 'Transform',
  '부스터': 'Booster',
  '페이스리프트': 'Facelift',
  '이노베이션': 'Innovation',
  '어반': 'Urban',
  '익스프레스': 'Express',
  '스페이스': 'Space',
  '프리미엄': 'Premium',
  '더마스터': 'The Master',
  '더 마스터': 'The Master',
  '일렉트릭': 'Electric',
  '2.0T': '2.0T',
  '더 SUV': 'The SUV',
  'SUV': 'SUV',
  'NARROW': 'Narrow',
  'WIDE': 'Wide',
  '플러스': 'Plus',
  '쿱': 'Koup',
};

// Модификаторы (не входят в имя-идентичность авто)
export const MODIFIERS = {
  '하이브리드': 'Hybrid',
  '전기차': 'EV',
  '수소차': 'FCEV',
  '디젤': 'Diesel',
  '가솔린': 'Gasoline',
  'LPI': 'LPI',
  'LPG': 'LPG',
  '터보': 'Turbo',
  '특장': 'Special Body',
  '전기형': 'Early',
  '후기형': 'Late',
  '수동': 'Manual',
  '오토': 'Auto',
  '구형': 'Early',
  '신형': 'Late',
  '구': 'Early',
  '신': 'Late',
  '누우엔진': 'Nu Engine',
  '누우': 'Nu Engine',
};
