-- Проверки по VIN: журнал обращений к внешним реестрам.
--
-- Заведён 30.08.2026 ради ограничения частоты — пять проверок в сутки на аккаунт
-- (решение владельца). Считать их в localStorage браузера нельзя: очистка хранилища
-- и режим инкогнито обнуляют счётчик, а защищаемся мы ровно от того, кто это сделает.
-- Проверка и так за входом, значит сервер знает пользователя, и лимиту место здесь.
--
-- Таблица журнальная, а не счётчик одной строкой, по двум причинам:
--
--   1. Окно скользящее (последние 24 часа), а не календарные сутки. Счётчик потребовал
--      бы решить, чья это полночь — корейская, московская или UTC, — и раз в сутки
--      давал бы всплеск. По журналу окно считается запросом и вопроса о поясе нет.
--   2. Это данные о спросе. Какие машины проверяют — тот же сигнал, что артикулы
--      в каталоге: видно, чем интересуются, ещё до всякой заявки.
--
-- Отсюда же оговорка про приватность: здесь VIN, привязанный к аккаунту. Это данные
-- покупателя, и попадать они должны в тот же периметр, что почта и телефон
-- в `partsfit_customers` — то есть в политику обработки данных.
--
-- Префикс `partsfit_` обязателен у каждого объекта, включая индексы: база общая
-- с kmotors, и пространство имён у индексов с таблицами одно.

create table if not exists partsfit_vin_lookups (
  id            bigint generated by default as identity primary key,

  -- Каскад: удалили аккаунт — исчезла и история его проверок. Без каскада VIN'ы
  -- пережили бы человека, попросившего себя удалить.
  user_id       uuid not null references auth.users (id) on delete cascade,

  -- Нормализованный номер: заглавные, без разделителей. Приводит его сервер.
  vin           text not null check (char_length(vin) between 11 and 17),

  -- Что ответил корейский реестр: found / not-found / unavailable. Нужно, чтобы
  -- отличать «проверили и нашли» от «реестр молчал» при разборе спроса.
  registry      text not null default 'unknown',

  looked_up_at  timestamptz not null default now()
);

-- Единственный горячий запрос: сколько раз этот пользователь ходил за последние сутки.
create index if not exists partsfit_vin_lookups_user_time_idx
  on partsfit_vin_lookups (user_id, looked_up_at desc);

-- Для разбора спроса: какие номера проверяют чаще.
create index if not exists partsfit_vin_lookups_vin_idx
  on partsfit_vin_lookups (vin);

-- Права явно. Таблица из миграции получает `anon`/`authenticated` только TRUNCATE,
-- REFERENCES и TRIGGER, а `grant` проверяется раньше RLS — без этих строк политика
-- ниже не открывает ничего.
--
-- `insert` вошедшему НЕ даётся намеренно: строку заводит только роут ключом
-- service_role. Позволь мы браузеру писать сюда — он мог бы и не писать,
-- то есть обойти лимит, ради которого таблица и заведена.
grant select on partsfit_vin_lookups to authenticated;
grant all    on partsfit_vin_lookups to service_role;

-- И явный отзыв у `anon`: на боевой базе умолчания не такие, как на локальном стеке —
-- там право на чтение новым таблицам достаётся анонимному ключу само.
revoke all on table partsfit_vin_lookups from anon;

alter table partsfit_vin_lookups enable row level security;

-- Свою историю вошедший видит, чужую — нет.
drop policy if exists partsfit_vin_lookups_select_own on partsfit_vin_lookups;
create policy partsfit_vin_lookups_select_own on partsfit_vin_lookups
  for select to authenticated
  using (auth.uid() = user_id);

-- PostgREST держит схему в кэше: без перезагрузки таблица есть, а REST по ней 404.
notify pgrst, 'reload schema';
